import type { LucideIcon } from "lucide-react";
import {
  Wifi,
  Home,
  Lightbulb,
  CreditCard,
  Car,
  Phone,
  Wallet,
  Zap,
  Droplets,
  Flame,
  ShoppingCart,
  Music,
  Tv,
  Coffee,
  Dumbbell,
  Receipt,
  CalendarDays,
  PieChart,
  TrendingUp,
  Download,
  Settings,
  KeyRound,
} from "lucide-react";
import type { AppSettings, BillGroup } from "@/types/settings";
import type { Bill, Section } from "@/types/bill";

export const ICON_MAP: Record<string, LucideIcon> = {
  Wifi,
  Home,
  Lightbulb,
  CreditCard,
  Car,
  Phone,
  Wallet,
  Zap,
  Droplets,
  Flame,
  ShoppingCart,
  Music,
  Tv,
  Coffee,
  Dumbbell,
};

export const ICON_OPTIONS: { key: string; label: string }[] = [
  { key: "Wifi", label: "Internet" },
  { key: "Lightbulb", label: "Electric" },
  { key: "Home", label: "Rent" },
  { key: "CreditCard", label: "Card" },
  { key: "Car", label: "Car" },
  { key: "Phone", label: "Phone" },
  { key: "Wallet", label: "Other" },
  { key: "Zap", label: "Utility" },
  { key: "Droplets", label: "Water" },
  { key: "Flame", label: "Gas" },
  { key: "ShoppingCart", label: "Shop" },
  { key: "Music", label: "Stream" },
  { key: "Tv", label: "Cable" },
  { key: "Coffee", label: "Coffee" },
  { key: "Dumbbell", label: "Gym" },
];

export const TINT_OPTIONS: { value: string; label: string; dot: string }[] = [
  { value: "bg-mint text-mint-deep", label: "Mint", dot: "bg-mint-deep" },
  {
    value: "bg-blush text-blush-deep",
    label: "Blush",
    dot: "bg-blush-deep",
  },
  {
    value: "bg-lilac text-lilac-deep",
    label: "Lilac",
    dot: "bg-lilac-deep",
  },
  {
    value: "bg-butter text-[oklch(0.62_0.1_80)]",
    label: "Butter",
    dot: "bg-[oklch(0.62_0.1_80)]",
  },
];

export const CATEGORY_TINT: Record<string, string> = {
  Utilities: "bg-mint text-mint-deep",
  Housing: "bg-lilac text-lilac-deep",
  Insurance: "bg-blush text-blush-deep",
  Subscriptions: "bg-lilac text-lilac-deep",
  Transportation: "bg-mint text-mint-deep",
  Other: "bg-butter text-[oklch(0.62_0.1_80)]",
};

export const PRIORITY_COLORS: Record<string, string> = {
  "0": "bg-blush text-blush-deep",
  "1": "bg-butter text-[oklch(0.62_0.1_80)]",
  "2": "bg-mint text-mint-deep",
  "3": "bg-lilac text-lilac-deep",
  "4": "bg-lilac text-lilac-deep",
};

export const DEFAULT_SETTINGS: AppSettings = {
  currency: "$",
  currencyPosition: "before",
  weekStart: "Sunday",
  priorityNames: ["Critical", "High", "Medium", "Low", "Optional"],
  categoryNames: ["Utilities", "Housing", "Insurance", "Subscriptions", "Other"],
  menuVisible: true,
  quickStartVisible: true,
  contactVisible: true,
};

export const DEFAULT_BILL_GROUPS: BillGroup[] = [
  {
    title: "Utilities",
    names: ["Electricity", "Water", "Gas", "Internet", "Phone"],
  },
  {
    title: "Housing",
    names: ["Rent", "Mortgage", "HOA", "Property Tax"],
  },
  {
    title: "Insurance",
    names: [
      "Car Insurance",
      "Home Insurance",
      "Health Insurance",
      "Life Insurance",
    ],
  },
  {
    title: "Subscriptions",
    names: ["Netflix", "Spotify", "Disney+", "Amazon Prime", "Claude"],
  },
  { title: "Other", names: ["Credit Card", "Loan Payment"] },
];

export const UNLOCK_CODE_HASH = "22be9918546fc3d06fbc14b64abe36750ebc576ceeb5bb6b53a59eb21c60a1cd";

export const FULL_CURRENCIES = [
  { symbol: "$", label: "US Dollar ($)" },
  { symbol: "€", label: "Euro (€)" },
  { symbol: "£", label: "British Pound (£)" },
  { symbol: "¥", label: "Japanese Yen (¥)" },
  { symbol: "₹", label: "Indian Rupee (₹)" },
  { symbol: "Rs", label: "Pakistani Rupee (Rs)" },
  { symbol: "₩", label: "South Korean Won (₩)" },
  { symbol: "₦", label: "Nigerian Naira (₦)" },
  { symbol: "R", label: "South African Rand (R)" },
  { symbol: "CHF", label: "Swiss Franc (CHF)" },
  { symbol: "CA$", label: "Canadian Dollar (CA$)" },
  { symbol: "A$", label: "Australian Dollar (A$)" },
  { symbol: "NZ$", label: "New Zealand Dollar (NZ$)" },
  { symbol: "S$", label: "Singapore Dollar (S$)" },
  { symbol: "HK$", label: "Hong Kong Dollar (HK$)" },
  { symbol: "kr", label: "Swedish Krona (kr)" },
  { symbol: "NOK", label: "Norwegian Krone (NOK)" },
  { symbol: "DKK", label: "Danish Krone (DKK)" },
  { symbol: "zł", label: "Polish Zloty (zł)" },
  { symbol: "Kč", label: "Czech Koruna (Kč)" },
  { symbol: "Ft", label: "Hungarian Forint (Ft)" },
  { symbol: "lei", label: "Romanian Leu (lei)" },
  { symbol: "₴", label: "Ukrainian Hryvnia (₴)" },
  { symbol: "₺", label: "Turkish Lira (₺)" },
  { symbol: "﷼", label: "Saudi Riyal (﷼)" },
  { symbol: "AED", label: "UAE Dirham (AED)" },
  { symbol: "QR", label: "Qatari Riyal (QR)" },
  { symbol: "KWD", label: "Kuwaiti Dinar (KWD)" },
  { symbol: "BHD", label: "Bahraini Dinar (BHD)" },
  { symbol: "OMR", label: "Omani Rial (OMR)" },
  { symbol: "JOD", label: "Jordanian Dinar (JOD)" },
  { symbol: "EGP", label: "Egyptian Pound (EGP)" },
  { symbol: "MAD", label: "Moroccan Dirham (MAD)" },
  { symbol: "TND", label: "Tunisian Dinar (TND)" },
  { symbol: "GHS", label: "Ghanaian Cedi (GHS)" },
  { symbol: "KES", label: "Kenyan Shilling (KES)" },
  { symbol: "ETB", label: "Ethiopian Birr (ETB)" },
  { symbol: "TZS", label: "Tanzanian Shilling (TZS)" },
  { symbol: "UGX", label: "Ugandan Shilling (UGX)" },
  { symbol: "XOF", label: "West African CFA (XOF)" },
  { symbol: "MX$", label: "Mexican Peso (MX$)" },
  { symbol: "R$", label: "Brazilian Real (R$)" },
  { symbol: "ARS", label: "Argentine Peso (ARS)" },
  { symbol: "CLP", label: "Chilean Peso (CLP)" },
  { symbol: "COP", label: "Colombian Peso (COP)" },
  { symbol: "PEN", label: "Peruvian Sol (PEN)" },
  { symbol: "VES", label: "Venezuelan Bolívar (VES)" },
  { symbol: "CRC", label: "Costa Rican Colón (CRC)" },
  { symbol: "GTQ", label: "Guatemalan Quetzal (GTQ)" },
  { symbol: "₱", label: "Philippine Peso (₱)" },
  { symbol: "Rp", label: "Indonesian Rupiah (Rp)" },
  { symbol: "RM", label: "Malaysian Ringgit (RM)" },
  { symbol: "฿", label: "Thai Baht (฿)" },
  { symbol: "₫", label: "Vietnamese Dong (₫)" },
  { symbol: "₭", label: "Lao Kip (₭)" },
  { symbol: "K", label: "Myanmar Kyat (K)" },
  { symbol: "৳", label: "Bangladeshi Taka (৳)" },
  { symbol: "LKR", label: "Sri Lankan Rupee (LKR)" },
  { symbol: "NPR", label: "Nepalese Rupee (NPR)" },
  { symbol: "AFN", label: "Afghan Afghani (AFN)" },
  { symbol: "GEL", label: "Georgian Lari (GEL)" },
  { symbol: "AMD", label: "Armenian Dram (AMD)" },
  { symbol: "AZN", label: "Azerbaijani Manat (AZN)" },
  { symbol: "KZT", label: "Kazakhstani Tenge (KZT)" },
  { symbol: "UZS", label: "Uzbekistani Som (UZS)" },
  { symbol: "MNT", label: "Mongolian Tögrög (MNT)" },
];

export const BUDGET_CAT_ICONS: LucideIcon[] = [
  Lightbulb,
  Home,
  Wallet,
  Wallet,
  Wallet,
];
export const BUDGET_CAT_BG = [
  "bg-blush/10",
  "bg-butter/15",
  "bg-blush/10",
  "bg-mint/15",
  "bg-blush/15",
];
export const BUDGET_CHART_COLORS = [
  "#9b7ecc",
  "#5aaa88",
  "#c97b7d",
  "#c5a44a",
  "#8ab0cc",
  "#b0c0a8",
];

export const MONTHS_SHORT = [
  "Jan",
  "Feb",
  "Mar",
  "Apr",
  "May",
  "Jun",
  "Jul",
  "Aug",
  "Sep",
  "Oct",
  "Nov",
  "Dec",
];

export const YEARLY_CAT_HEADER = [
  "bg-blush-deep text-white",
  "bg-[oklch(0.72_0.1_80)] text-white",
  "bg-mint-deep text-white",
  "bg-lilac-deep text-white",
  "bg-blush-deep/80 text-white",
];
export const YEARLY_CAT_BAR_FILL = [
  "#c97b7d",
  "#c5a44a",
  "#5aaa88",
  "#9b7ecc",
  "#c97b7d",
];

export const NAV_ITEMS: { label: Section; icon: LucideIcon }[] = [
  { label: "Dashboard", icon: Home },
  { label: "Bills", icon: Receipt },
  { label: "Calendar", icon: CalendarDays },
  { label: "Budget", icon: PieChart },
  { label: "Yearly Overview", icon: TrendingUp },
  { label: "Backup", icon: Download },
  { label: "Settings", icon: Settings },
  ...(import.meta.env.VITE_CUSTOMER_BUILD === "true"
    ? []
    : [{ label: "Management" as Section, icon: KeyRound }]),
];

export const SEED_BILLS: Bill[] = [
  {
    id: "seed-1",
    seriesId: "seed-1",
    name: "Internet",
    amount: 60,
    actualAmount: null,
    dueDate: "2026-08-20",
    actualDate: null,
    iconKey: "Wifi",
    tint: "bg-mint text-mint-deep",
    paid: false,
    category: "Utilities",
    priority: 2,
    frequency: "monthly",
    interval: 1,
    endDate: null,
    notes: "",
    type: "payment",
  },
  {
    id: "seed-2",
    seriesId: "seed-2",
    name: "Electricity",
    amount: 85,
    actualAmount: null,
    dueDate: "2026-08-22",
    actualDate: null,
    iconKey: "Lightbulb",
    tint: "bg-blush text-blush-deep",
    paid: false,
    category: "Utilities",
    priority: 1,
    frequency: "monthly",
    interval: 1,
    endDate: null,
    notes: "",
    type: "payment",
  },
  {
    id: "seed-3",
    seriesId: "seed-3",
    name: "Rent",
    amount: 950,
    actualAmount: null,
    dueDate: "2026-08-25",
    actualDate: null,
    iconKey: "Home",
    tint: "bg-lilac text-lilac-deep",
    paid: false,
    category: "Housing",
    priority: 0,
    frequency: "monthly",
    interval: 1,
    endDate: null,
    notes: "",
    type: "payment",
  },
  {
    id: "seed-4",
    seriesId: "seed-4",
    name: "Credit Card",
    amount: 178,
    actualAmount: null,
    dueDate: "2026-08-28",
    actualDate: null,
    iconKey: "CreditCard",
    tint: "bg-butter text-[oklch(0.62_0.1_80)]",
    paid: false,
    category: "Other",
    priority: 1,
    frequency: "monthly",
    interval: 1,
    endDate: null,
    notes: "",
    type: "payment",
  },
  {
    id: "seed-5",
    seriesId: "seed-5",
    name: "Car Insurance",
    amount: 120,
    actualAmount: null,
    dueDate: "2026-08-05",
    actualDate: null,
    iconKey: "Car",
    tint: "bg-mint text-mint-deep",
    paid: false,
    category: "Insurance",
    priority: 2,
    frequency: "monthly",
    interval: 1,
    endDate: null,
    notes: "",
    type: "payment",
  },
  {
    id: "seed-6",
    seriesId: "seed-6",
    name: "Phone Bill",
    amount: 75,
    actualAmount: null,
    dueDate: "2026-09-05",
    actualDate: null,
    iconKey: "Phone",
    tint: "bg-blush text-blush-deep",
    paid: false,
    category: "Utilities",
    priority: 2,
    frequency: "monthly",
    interval: 1,
    endDate: null,
    notes: "",
    type: "payment",
  },
];
